Fixes #23
percolate/ec2-security-groups-dumper pull request #25
Opened 2018-12-13 12:25 UTC by rk295

I also found having the VpcId in the output useful, so I took the
liberty to add it.

I appreciate this might be a breaking change if somebody is depending on
the output of this tool.

2018-12-13 19:44 UTC, lra requested changes
I got an error on the csv output:
```
Traceback (most recent call last):
  File "/Users/analogue/.pyenv/versions/3.7.0/bin/ec2-security-groups-dumper", line 11, in <module>
    load_entry_point('ec2-security-groups-dumper', 'console_scripts', 'ec2-security-groups-dumper')()
  File "/Users/analogue/src/ec2-security-groups-dumper/ec2_security_groups_dumper/main.py", line 390, in main
    print(firewall.csv)
  File "/Users/analogue/src/ec2-security-groups-dumper/ec2_security_groups_dumper/main.py", line 281, in csv
    for fr in self.rules:
  File "/Users/analogue/src/ec2-security-groups-dumper/ec2_security_groups_dumper/main.py", line 224, in rules
    main_row['vpc_id'])
  File "/Users/analogue/src/ec2-security-groups-dumper/ec2_security_groups_dumper/main.py", line 66, in __init__
    assert isinstance(vpc_id, str)
AssertionError
```

2018-12-13 22:50 UTC, rk295 commented
I've pushed a minor tweak, the JSON output was incorrect. 

I'm a bit confused about that AssertionError, what is the AWS API returning for `VpcId` for you? I've tried it against a bunch of AWS accounts I have and all seem fine.

The only thing I can think of is maybe you have some Security Groups for the pre VPC era and the VpcId field is being returned as `null` or something?

2018-12-14 01:19 UTC, lra commented
Yes, I have some old classic stuff around, and in this case, the `vpc_id` is a `NoneType`.

2018-12-14 10:31 UTC, rk295 commented
I'm not sure how you'd prefer this fixed, I've pushed a commit which works around the lack of the `VpcId` field by defaulting it to an empty string. See line 316.

2018-12-14 18:14 UTC, lra requested changes
Looks good, just a few comments to embrace the fact that a VPC is optional due to classic.

2018-12-14 18:14 UTC, lra commented on ec2_security_groups_dumper/main.py
> +        assert isinstance(vpc_id, str)
Taking classic into account, a firewall rule does not need to be in a VPC, so let's make this `str` or `NoneType`.

2018-12-14 18:14 UTC, lra commented on ec2_security_groups_dumper/main.py
> +                 vpc_id,
make it default to None to support classic.

2018-12-14 18:14 UTC, lra commented on ec2_security_groups_dumper/main.py
> +                                    main_row['vpc_id'],
You can use a named param as `vpc_id` is optional.

2018-12-14 18:14 UTC, lra commented on ec2_security_groups_dumper/main.py
> +                                    main_row['vpc_id'],
ditto

2018-12-14 18:14 UTC, lra commented on ec2_security_groups_dumper/main.py
> +                            main_row['vpc_id'],
ditto

2018-12-14 18:14 UTC, lra commented on ec2_security_groups_dumper/main.py
> +                                  main_row['vpc_id'])
ditto

2018-12-14 18:14 UTC, lra commented on ec2_security_groups_dumper/main.py
> +            group_dict['vpc_id'] = group.get('VpcId', "")
Like the optional fields use `None` instead of an empty string.

2025-08-10 18:10 UTC, closed without merging